WHENEVER OSERROR EXIT SQL.SQLCODE
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON
SPOOL disable_logarchiving.log
CONNECT "SYS"/&1 AS SYSDBA
SHUTDOWN IMMEDIATE
CONNECT "SYS"/&1 AS SYSDBA
STARTUP MOUNT;
ALTER DATABASE NOARCHIVELOG;
ALTER DATABASE OPEN;
SPOOL OFF
EXIT;
