WHENEVER OSERROR EXIT SQL.SQLCODE
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
SET ECHO OFF
BTITLE OFF
TTITLE OFF
CONNECT / as sysdba;
--startup mount;
--shutdown immediate;
--CONNECT / as sysdba;
startup;
EXIT SUCCESS;